version: "3.8"

services:
  gateway:
    build:
      context: ./api-gateway/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network

  user-service:
    build:
      context: ./users-service
    networks:
      - app-network

  product-service:
    build:
      context: ./products-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
